AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla Basica


Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SSHSecurityGroup-2
      GroupDescription: grupo de seguridad para ssh
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-005fc0f236362e99f"
      KeyName: vockey
      InstanceType: t2.small
      SecurityGroups: 
        - !Ref InstanceSecurityGroup
      Tags: 
        - Key: Name 
          Value: tomcat
    
    


    