AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla Basica


# Recursos
Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: rmtrafamaldonadotriana.myfirst.bucket
    